app/base/models.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from flask_login import UserMixin
from sqlalchemy import Binary, Column, Integer, String

from app import db, login_manager

from app.base.util import hash_pass

class User(db.Model, UserMixin):

    __tablename__ = 'User'

    id = Column(Integer, primary_key=True)
    username = Column(String, unique=True)
    email = Column(String, unique=True)
    password = Column(Binary)

    def __init__(self, **kwargs):
        for property, value in kwargs.items():
            # depending on whether value is an iterable or not, we must
            # unpack it's value (when **kwargs is request.form, some values
            # will be a 1-element list)
            if hasattr(value, '__iter__') and not isinstance(value, str):
                # the ,= unpack of a singleton fails PEP8 (travis flake8 test)
                value = value[0]

            if property == 'password':
                value = hash_pass( value ) # we need bytes here (not plain str)
                
            setattr(self, property, value)

    def __repr__(self):
        return str(self.username)


@login_manager.user_loader
def user_loader(id):
    return User.query.filter_by(id=id).first()

@login_manager.request_loader
def request_loader(request):
    username = request.form.get('username')
    user = User.query.filter_by(username=username).first()
    return user if user else None

app/base/forms.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from flask_wtf import FlaskForm
from wtforms import TextField, PasswordField
from wtforms.validators import InputRequired, Email, DataRequired

## login and registration

class LoginForm(FlaskForm):
    username = TextField    ('Username', id='username_login'   , validators=[DataRequired()])
    password = PasswordField('Password', id='pwd_login'        , validators=[DataRequired()])

class CreateAccountForm(FlaskForm):
    username = TextField('Username'     , id='username_create' , validators=[DataRequired()])
    email    = TextField('Email'        , id='email_create'    , validators=[DataRequired(), Email()])
    password = PasswordField('Password' , id='pwd_create'      , validators=[DataRequired()])

app/base/__init__.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from flask import Blueprint

blueprint = Blueprint(
    'base_blueprint',
    __name__,
    url_prefix='',
    template_folder='templates',
    static_folder='static'
)

app/base/routes.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from flask import jsonify, render_template, redirect, request, url_for
from flask_login import (
    current_user,
    login_required,
    login_user,
    logout_user
)

from app import db, login_manager
from app.base import blueprint
from app.base.forms import LoginForm, CreateAccountForm
from app.base.models import User

from app.base.util import verify_pass

@blueprint.route('/')
def route_default():
    return redirect(url_for('base_blueprint.login'))

@blueprint.route('/error-<error>')
def route_errors(error):
    return render_template('errors/{}.html'.format(error))

## Login & Registration

@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm(request.form)
    if 'login' in request.form:
        
        # read form data
        username = request.form['username']
        password = request.form['password']

        # Locate user
        user = User.query.filter_by(username=username).first()
        
        # Check the password
        if user and verify_pass( password, user.password):

            login_user(user)
            return redirect(url_for('base_blueprint.route_default'))

        # Something (user or pass) is not ok
        return render_template( 'login/login.html', msg='Wrong user or password', form=login_form)

    if not current_user.is_authenticated:
        return render_template( 'login/login.html',
                                form=login_form)
    return redirect(url_for('home_blueprint.index'))

@blueprint.route('/create_user', methods=['GET', 'POST'])
def create_user():
    login_form = LoginForm(request.form)
    create_account_form = CreateAccountForm(request.form)
    if 'register' in request.form:

        username  = request.form['username']
        email     = request.form['email'   ]

        user = User.query.filter_by(username=username).first()
        if user:
            return render_template( 'login/register.html', msg='Username already registered', form=create_account_form)

        user = User.query.filter_by(email=email).first()
        if user:
            return render_template( 'login/register.html', msg='Email already registered', form=create_account_form)

        # else we can create the user
        user = User(**request.form)
        db.session.add(user)
        db.session.commit()

        return render_template( 'login/register.html', msg='User created please <a href="/login">login</a>', form=create_account_form)

    else:
        return render_template( 'login/register.html', form=create_account_form)

@blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('base_blueprint.login'))

@blueprint.route('/shutdown')
def shutdown():
    func = request.environ.get('werkzeug.server.shutdown')
    if func is None:
        raise RuntimeError('Not running with the Werkzeug Server')
    func()
    return 'Server shutting down...'

## Errors

@login_manager.unauthorized_handler
def unauthorized_handler():
    return render_template('errors/403.html'), 403

@blueprint.errorhandler(403)
def access_forbidden(error):
    return render_template('errors/403.html'), 403

@blueprint.errorhandler(404)
def not_found_error(error):
    return render_template('errors/404.html'), 404

@blueprint.errorhandler(500)
def internal_error(error):
    return render_template('errors/500.html'), 500

app/base/templates/base-site-fullscreen.html
<!DOCTYPE html>
<!--
* CoreUI - Free Bootstrap Admin Template
* @version v3.0.0-alpha.1
* @link https://coreui.io
* Copyright (c) 2019 creativeLabs Łukasz Holeczek
* Licensed under MIT (https://coreui.io/license)
-->
<html lang="en">
  <head>
    
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta name="description" content="CoreUI - Open Source Bootstrap Admin Template">
    <meta name="author" content="Łukasz Holeczek">
    <meta name="keyword" content="Bootstrap,Admin,Template,Open,Source,jQuery,CSS,HTML,RWD,Dashboard">
    
    <title>
        Flask Dashboard CoreUI - {% block title %}{% endblock %} | AppSeed
    </title>

    <link rel="apple-touch-icon" sizes="57x57" href="/static/assets/favicon/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/static/assets/favicon/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/static/assets/favicon/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/static/assets/favicon/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/static/assets/favicon/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/static/assets/favicon/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/static/assets/favicon/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/static/assets/favicon/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/static/assets/favicon/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192" href="/static/assets/favicon/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/static/assets/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/static/assets/favicon/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/static/assets/favicon/favicon-16x16.png">
    <link rel="manifest" href="/static/assets/favicon/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/static/assets/favicon/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">

    <!-- Icons-->
    <link href="/static/assets/vendors/@coreui/icons/css/free.min.css" rel="stylesheet">
    <link href="/static/assets/vendors/flag-icon-css/css/flag-icon.min.css" rel="stylesheet">

    <!-- Main styles for this application-->
    <link href="/static/assets/css/style.css" rel="stylesheet">
    <link href="/static/assets/vendors/pace-progress/css/pace.min.css" rel="stylesheet">

    <!-- Specific Page CSS goes HERE  -->  
    {% block stylesheets %}{% endblock stylesheets %}

  </head>
  <body class="c-app flex-row align-items-center">

    <div class="container">

        {% block content %}{% endblock content %}
    
    </div>

    {% include 'site_template/scripts.html' %}

    <!-- Specific Page JS goes HERE  -->
    {% block javascripts %}{% endblock javascripts %}

  </body>
</html>

app/base/templates/login/login.html
{% extends "base-site-fullscreen.html" %}

{% block title %} Login {% endblock %}

{% block content %}

    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="card-group">
          <div class="card p-4">
          
            <form role="form" method="post" action="">

              {{ form.hidden_tag() }} 

              <div class="card-body">

                <div class="text-center">
                  <h2>
                    <a href="https://appseed.us/admin-dashboards/flask-dashboard-coreui" >Flask Dashboard CoreUI</a>
                  </h2>
                  <h5>Login</h5>
                  <p class="text-muted">

                    {% if msg %}
                      {{ msg | safe }}
                    {% else %}
                    <span>
                      Use default credentials: <strong>test / pass</strong>
                      <br />
                      OR <a href={{ url_for('base_blueprint.create_user') }} >create your own user</a>
                    </span>
                    {% endif %}

                  </p>
                </div>

                <br />

                <div class="input-group mb-3">
                  <div class="input-group-prepend"><span class="input-group-text">
                      <svg class="c-icon">
                        <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-user"></use>
                      </svg></span></div>
                  {{ form.username(placeholder="Username", class="form-control") }}
                </div>

                <div class="input-group mb-4">
                  <div class="input-group-prepend"><span class="input-group-text">
                      <svg class="c-icon">
                        <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-lock-locked"></use>
                      </svg></span></div>
                  {{ form.password(placeholder="Password", class="form-control", type="password") }}
                </div>

                <br />

                <div class="text-center">
                    <button type="submit" name="login" class="btn btn-primary px-4">Login</button>
                </div>

              </div>
            
            </form>  

            <div class="card-footer p-4 text-center">
                Don't have an account? <a href={{ url_for('base_blueprint.create_user') }} >Register</a>
            </div>
              
          </div>
        </div>
      </div>
    </div>

{% endblock content %}

app/base/templates/site_template/footer.html
<footer class="c-footer">
    <div><a href="https://coreui.io">CoreUI</a> © 2019 creativeLabs.</div>
    <div class="ml-auto">Powered by&nbsp;<a href="https://coreui.io/">CoreUI</a></div>
</footer>
 

app/base/templates/site_template/navigation.html
      <header class="c-header c-header-light c-header-fixed c-header-with-subheader">
            <button class="c-header-toggler c-class-toggler d-lg-none mr-auto" type="button" data-target="#sidebar" data-class="c-sidebar-show"><span class="c-header-toggler-icon"></span></button><a class="c-header-brand d-sm-none" href="#"><img class="c-header-brand" src="/static/assets/brand/coreui-base.svg" width="97" height="46" alt="CoreUI Logo"></a>
            <button class="c-header-toggler c-class-toggler ml-3 d-md-down-none" type="button" data-target="#sidebar" data-class="c-sidebar-lg-show" responsive="true"><span class="c-header-toggler-icon"></span></button>
            <ul class="c-header-nav d-md-down-none">
              <li class="c-header-nav-item px-3"><a class="c-header-nav-link" href="#">Dashboard</a></li>
              <li class="c-header-nav-item px-3"><a class="c-header-nav-link" href="#">Users</a></li>
              <li class="c-header-nav-item px-3"><a class="c-header-nav-link" href="#">Settings</a></li>
            </ul>
            <ul class="c-header-nav ml-auto mr-4">
              <li class="c-header-nav-item d-md-down-none mx-2"><a class="c-header-nav-link" href="#">
                  <svg class="c-icon">
                    <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-bell"></use>
                  </svg></a></li>
              <li class="c-header-nav-item d-md-down-none mx-2"><a class="c-header-nav-link" href="#">
                  <svg class="c-icon">
                    <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-list-rich"></use>
                  </svg></a></li>
              <li class="c-header-nav-item d-md-down-none mx-2"><a class="c-header-nav-link" href="#">
                  <svg class="c-icon">
                    <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-envelope-open"></use>
                  </svg></a></li>
              <li class="c-header-nav-item dropdown"><a class="c-header-nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                  <div class="c-avatar"><img class="c-avatar-img" src="/static/assets/img/avatars/6.jpg" alt="user@email.com"></div>
                </a>
                <div class="dropdown-menu dropdown-menu-right pt-0">
                  <div class="dropdown-header bg-light py-2"><strong>Account</strong></div><a class="dropdown-item" href="#">
                    <svg class="c-icon mr-2">
                      <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-bell"></use>
                    </svg> Updates<span class="badge badge-info ml-auto">42</span></a><a class="dropdown-item" href="#">
                    <svg class="c-icon mr-2">
                      <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-envelope-open"></use>
                    </svg> Messages<span class="badge badge-success ml-auto">42</span></a><a class="dropdown-item" href="#">
                    <svg class="c-icon mr-2">
                      <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-task"></use>
                    </svg> Tasks<span class="badge badge-danger ml-auto">42</span></a><a class="dropdown-item" href="#">
                    <svg class="c-icon mr-2">
                      <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-comment-square"></use>
                    </svg> Comments<span class="badge badge-warning ml-auto">42</span></a>
                  <div class="dropdown-header bg-light py-2"><strong>Settings</strong></div><a class="dropdown-item" href="#">
                    <svg class="c-icon mr-2">
                      <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-user"></use>
                    </svg> Profile</a><a class="dropdown-item" href="#">
                    <svg class="c-icon mr-2">
                      <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-settings"></use>
                    </svg> Settings</a><a class="dropdown-item" href="#">
                    <svg class="c-icon mr-2">
                      <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-credit-card"></use>
                    </svg> Payments<span class="badge badge-secondary ml-auto">42</span></a><a class="dropdown-item" href="#">
                    <svg class="c-icon mr-2">
                      <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-file"></use>
                    </svg> Projects<span class="badge badge-primary ml-auto">42</span></a>
                  <div class="dropdown-divider"></div><a class="dropdown-item" href="#">
                    <svg class="c-icon mr-2">
                      <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-lock-locked"></use>
                    </svg> Lock Account</a><a class="dropdown-item" href={{ url_for('base_blueprint.logout') }} >
                    <svg class="c-icon mr-2">
                      <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-account-logout"></use>
                    </svg> Logout</a>
                </div>
              </li>
            </ul>
            <div class="c-subheader px-3">
              <!-- Breadcrumb-->
              <ol class="breadcrumb border-0 m-0">
                <li class="breadcrumb-item">Home</li>
                <li class="breadcrumb-item"><a href="#">Admin</a></li>
                <li class="breadcrumb-item active">Dashboard</li>
                <!-- Breadcrumb Menu-->
              </ol>
            </div>
          </header>
    

app/base/templates/site_template/sidebar.html
    <div class="c-sidebar c-sidebar-dark c-sidebar-fixed c-sidebar-lg-show" id="sidebar">
            <div class="c-sidebar-brand"><img class="c-sidebar-brand-full" src="/static/assets/brand/coreui-base-white.svg" width="118" height="46" alt="CoreUI Logo"><img class="c-sidebar-brand-minimized" src="/static/assets/brand/coreui-signet-white.svg" width="118" height="46" alt="CoreUI Logo"></div>
            <ul class="c-sidebar-nav">
              <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/">
                  <svg class="c-sidebar-nav-icon">
                    <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-speedometer"></use>
                  </svg> Dashboard<span class="badge badge-info">NEW</span></a></li>
              <li class="c-sidebar-nav-title">Theme</li>
              <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/page-colors">
                  <svg class="c-sidebar-nav-icon">
                    <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-drop1"></use>
                  </svg> Colors</a></li>
              <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/page-typography">
                  <svg class="c-sidebar-nav-icon">
                    <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-pencil"></use>
                  </svg> Typography</a></li>
              <li class="c-sidebar-nav-title">Components</li>
              <li class="c-sidebar-nav-item c-sidebar-nav-dropdown"><a class="c-sidebar-nav-link c-sidebar-nav-dropdown-toggle" href="#">
                  <svg class="c-sidebar-nav-icon">
                    <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-puzzle"></use>
                  </svg> Base</a>
                <ul class="c-sidebar-nav-dropdown-items">
                  <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/base-breadcrumb"><span class="c-sidebar-nav-icon"></span> Breadcrumb</a></li>
                  <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/base-cards"><span class="c-sidebar-nav-icon"></span> Cards</a></li>
                  <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/base-carousel"><span class="c-sidebar-nav-icon"></span> Carousel</a></li>
                  <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/base-collapse"><span class="c-sidebar-nav-icon"></span> Collapse</a></li>
                  <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/base-forms"><span class="c-sidebar-nav-icon"></span> Forms</a></li>
                  <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/base-jumbotron"><span class="c-sidebar-nav-icon"></span> Jumbotron</a></li>
                  <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/base-list-group"><span class="c-sidebar-nav-icon"></span> List group</a></li>
                  <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/base-navs"><span class="c-sidebar-nav-icon"></span> Navs</a></li>
                  <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/base-pagination"><span class="c-sidebar-nav-icon"></span> Pagination</a></li>
                  <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/base-popovers"><span class="c-sidebar-nav-icon"></span> Popovers</a></li>
                  <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/base-progress"><span class="c-sidebar-nav-icon"></span> Progress</a></li>
                  <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/base-scrollspy"><span class="c-sidebar-nav-icon"></span> Scrollspy</a></li>
                  <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/base-switches"><span class="c-sidebar-nav-icon"></span> Switches</a></li>
                  <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/base-tables"><span class="c-sidebar-nav-icon"></span> Tables</a></li>
                  <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/base-tabs"><span class="c-sidebar-nav-icon"></span> Tabs</a></li>
                  <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/base-tooltips"><span class="c-sidebar-nav-icon"></span> Tooltips</a></li>
                </ul>
              </li>
              <li class="c-sidebar-nav-item c-sidebar-nav-dropdown"><a class="c-sidebar-nav-link c-sidebar-nav-dropdown-toggle" href="#">
                  <svg class="c-sidebar-nav-icon">
                    <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-cursor"></use>
                  </svg> Buttons</a>
                <ul class="c-sidebar-nav-dropdown-items">
                  <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/buttons-regular"><span class="c-sidebar-nav-icon"></span> Buttons</a></li>
                  <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/buttons-group"><span class="c-sidebar-nav-icon"></span> Buttons Group</a></li>
                  <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/buttons-dropdowns"><span class="c-sidebar-nav-icon"></span> Dropdowns</a></li>
                  <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/buttons-brand"><span class="c-sidebar-nav-icon"></span> Brand Buttons</a></li>
                </ul>
              </li>
              <li class="c-sidebar-nav-dropdown"><a class="c-sidebar-nav-dropdown-toggle" href="#">
                  <svg class="c-sidebar-nav-icon">
                    <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-star"></use>
                  </svg> Icons</a>
                <ul class="c-sidebar-nav-dropdown-items">
                  <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/icons-coreui-free"> CoreUI Icons<span class="badge badge-success">Free</span></a></li>
                  <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/icons-coreui-brand"> CoreUI Icons - Brand</a></li>
                  <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/icons-coreui-flag"> CoreUI Icons - Flag</a></li>
                </ul>
              </li>
              <li class="c-sidebar-nav-item c-sidebar-nav-dropdown"><a class="c-sidebar-nav-link c-sidebar-nav-dropdown-toggle" href="#">
                  <svg class="c-sidebar-nav-icon">
                    <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-bell"></use>
                  </svg> Notifications</a>
                <ul class="c-sidebar-nav-dropdown-items">
                  <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/notifications-alerts"><span class="c-sidebar-nav-icon"></span> Alerts</a></li>
                  <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/notifications-badge"><span class="c-sidebar-nav-icon"></span> Badge</a></li>
                  <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/notifications-modals"><span class="c-sidebar-nav-icon"></span> Modals</a></li>
                </ul>
              </li>
              <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/page-widgets">
                  <svg class="c-sidebar-nav-icon">
                    <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-calculator"></use>
                  </svg> Widgets<span class="badge badge-info">NEW</span></a></li>

              <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/page-charts">
                  <svg class="c-sidebar-nav-icon">
                    <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-chart-pie"></use>
                  </svg> Charts</a></li>

              <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href={{ url_for('base_blueprint.logout') }} >
                  <svg class="c-sidebar-nav-icon">
                    <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-account-logout"></use>
                  </svg> Logout</a></li>

              <li class="c-sidebar-nav-divider"></li>
              <li class="c-sidebar-nav-title">Extras</li>
              <li class="c-sidebar-nav-item c-sidebar-nav-dropdown"><a class="c-sidebar-nav-link c-sidebar-nav-dropdown-toggle" href="#">
                  <svg class="c-sidebar-nav-icon">
                    <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-star"></use>
                  </svg> Pages</a>
                <ul class="c-sidebar-nav-dropdown-items">
                  <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/create_user" target="_top">
                      <svg class="c-sidebar-nav-icon">
                        <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-account-logout"></use>
                      </svg> Register</a></li>
                  <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/page-404" target="_top">
                      <svg class="c-sidebar-nav-icon">
                        <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-bug"></use>
                      </svg> Error 404</a></li>
                  <li class="c-sidebar-nav-item"><a class="c-sidebar-nav-link" href="/page-500" target="_top">
                      <svg class="c-sidebar-nav-icon">
                        <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-bug"></use>
                      </svg> Error 500</a></li>
                </ul>
              </li>
              <li class="c-sidebar-nav-item mt-auto"><a class="c-sidebar-nav-link c-sidebar-nav-link-success" 
                  href="https://appseed.us/admin-dashboards/flask-dashboard-coreui">
                  <svg class="c-sidebar-nav-icon">
                    <use xlink:href="/static/assets/vendors/@coreui/icons/svg/free.svg#cil-cloud-download"></use>
                  </svg> Product Info</a></li>
            </ul>
            <button class="c-sidebar-minimizer c-class-toggler" type="button" data-target="_parent" data-class="c-sidebar-minimized"></button>
          </div>
      